config/routes.rb
Rails.application.routes.draw do

  root 'events#index'
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :events, only: [:index, :show, :new, :create] do
    resources :invites, only: [:create]
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :creator, class_name: "User"
  has_many :invites, dependent: :destroy
  has_many :attendees, through: :invites
  scope :upcoming_events, -> { where("event_date > ?", Time.zone.now) }
  scope :past_events, -> { where("event_date < ?", Time.zone.now) }
  validates :location, :event_date, :creator_id, presence: true

end

app/models/invite.rb
class Invite < ActiveRecord::Base
  belongs_to :event
  belongs_to :attendee, class_name: "User"
  validates :attendee_id, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events, foreign_key: :creator_id
  has_many :invites, foreign_key: :attendee_id
  has_many :attended_events, through: :invites, source: :event

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
  end

  def create
    event = Event.new(location: params[:event][:location], creator_id: params[:event][:user_id], event_date: params[:event][:event_date])
    if event.save
      event.invites.create(attendee_id: params[:event][:user_id])
      redirect_to event_path(event)
    else
      redirect_to user_path(current_user)
    end
  end

end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController

  def create
    event = Event.find(params[:event_id])
    if user = User.find_by(name: params[:invite][:user_name])
      event.invites.create(attendee_id: user.id)
      redirect_to event_path(event.id)
    else
      flash[:danger] = "User does not exist"
      redirect_to event_path(event.id)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(name: params[:session][:name])
    if user
      log_in(user)
      redirect_to user
    else
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @upcoming_events = @user.events.upcoming_events
    @past_events = @user.events.past_events
  end

  def create
    @user = User.create(name: params[:user][:name])
    log_in @user
    redirect_to @user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper 
end

app/helpers/events_helper.rb
module EventsHelper

end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper


  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find(user_id)
    end
  end

  def log_out
    session.clear
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>All Events</h1>

<% @events.each do |e| %>
  <ul>
    <li><strong><%= link_to "#{e.location}", event_path(e) %></strong><%= "   " + e.event_date.to_s %></li>
  </ul>
<% end %>

app/views/events/show.html.erb
<h2><%= @event.location %> - <small>hosted by: <%= @event.creator.name %></small></h2>
<h3>Guests invited:</h3>
<% @event.attendees.each do |e| %>
  <ul>
    <li><%= link_to e.name, user_path(e) %></li>
  </ul>
<% end %>

<%= render 'invites/new_invite' %>

app/views/invites/_new_invite.html.erb
<% if current_user && @event.creator_id == current_user.id %>
  <h4>Invite Friends</h4>
  <%= "User does not exist!" if flash[:danger] %>
  <%= form_for :invite, url: event_invites_path(@event.id) do |f| %>
    Name: <%= f.text_field :user_name %>
    <%= f.submit "Invite" %>
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<div style="float: right; display: inline;">
  <% if logged_in? %>
    <strong>Signed in as: <small><%= link_to "#{@current_user.name}", user_path(@current_user.id) %></small></strong><br>
    <%= link_to "Log Out", session_path(@current_user.id), method: "delete" %>
  <% else %>
    <%= link_to "Sign in here", new_session_path %>
    <br>
    <%= link_to "New user?", new_user_path %>
  <% end %>
  <br><%= link_to "Home", root_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrivateEvents</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>
<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>New User Sign-Up</h1>

<%= form_for @user do |f| %>
  Name: <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1>User Page - <small><%= @user.name %></small></h1>


<% if @user == current_user %>
  <h3>Events Hosted</h3>
  <%= "None" if @user.events.empty? %>
  <% @user.events.each do |e| %>
    <ul>
      <li><strong><%= link_to "#{e.location}", event_path(e) %></strong> - <%= e.event_date.to_formatted_s(:long) %></li>
    </ul>
  <% end %>

  <h3>Future Events</h3>
  <%= "Not attending any future events" if @upcoming_events.empty? %>
  <% @upcoming_events.each do |e| %>
    <ul>
      <li><strong><%= link_to "#{e.location}", event_path(e) %></strong> - <%= e.event_date.to_formatted_s(:long) %></li>
    </ul>
  <% end %>

  <h3>Past Attended Events</h3>
  <%= "#{@user.name} did not attend any events" if @past_events.empty? %>
  <% @past_events.each do |e| %>
    <ul>
      <li><strong><%= link_to "#{e.location}", event_path(e) %></strong> - <%= e.event_date.to_formatted_s(:long) %></li>
    </ul>
  <% end %>

  <div>
    <h3>New Event</h3>
    <%= form_for :event, url: events_path do |f| %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.label :location, "Location/Name" %>
      <%= f.text_field :location %>
      <%= f.label :event_date %>
      <%= f.datetime_local_field :event_date %>
      <%= f.submit "Create New Event" %>
    <% end %>

  </div>
<% end %>